import java.text.SimpleDateFormat

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: "kotlin-allopen"
apply plugin: "kotlin-kapt"
apply plugin: "androidx.navigation.safeargs"


allOpen {
    annotation("org.androidannotations.api.KotlinOpen")
}

android {
    namespace 'me.skean.framework.example'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
        freeCompilerArgs += "-Xjvm-default=all-compatibility"
    }
    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true // 开启 BuildConfig 生成
        compose true      // 如果 App 也用 Compose 请开启
    }
    composeOptions {
        // Kotlin 1.8.10 对应 1.4.2
        // 如果你使用的是 Kotlin 1.8.20，请改为 1.4.7
        kotlinCompilerExtensionVersion "1.4.7"
    }
    signingConfigs {
        //todo 修改签名文件
        config {
            keyAlias 'test'
            keyPassword '123456'
            storeFile file('test.jks')
            storePassword '123456'
        }
    }
    def vcode = Integer.parseInt(VERSION_CODE)
    def vname = VERSION_NAME
    def isRelease = gradle.startParameter.taskRequests.any {
        it.args.any { it.endsWith("Release") }
    }
    if (isRelease) {
        vcode = vcode + 1
        def versionNameGroup = VERSION_NAME.split("\\.")
        def versionNamePart1 = Integer.parseInt(versionNameGroup[0])
        def versionNamePart2 = Integer.parseInt(versionNameGroup[1])
        def versionNamePart3 = Integer.parseInt(versionNameGroup[2])
        versionNamePart3 = versionNamePart3 + 1
        if (versionNamePart3 > 9) {
            versionNamePart3 = 0
            versionNamePart2 = versionNamePart2 + 1
            if (versionNamePart2 > 9) {
                versionNamePart2 = 0
                versionNamePart1 = versionNamePart1 + 1
            }
        }
        vname = versionNamePart1 + "." + versionNamePart2 + "." + versionNamePart3
        ant.propertyfile(file: "../gradle.properties") {
            entry(key: "VERSION_CODE", value: vcode)
            entry(key: "VERSION_NAME", value: vname)
        }
    }

    defaultConfig {
        //todo 修改程序ID
        applicationId "me.skean.framework.example"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode vcode
        versionName vname
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a"
        }

        kapt {
            arguments {
                arg('eventBusIndex', "${android.defaultConfig.applicationId}.EventBusIndex")
                arg('resourcePackageName', android.defaultConfig.applicationId)
                arg("room.schemaLocation", "$projectDir/schemas")
                arg('androidManifestFile', "$projectDir/src/main/AndroidManifest.xml")
            }
        }

        manifestPlaceholders = [rawApplicationId  : defaultConfig.applicationId,
                                AMAP_API_KEY      : "your_actual_key_or_empty",
                                PGYER_API_KEY     : "your_actual_key_or_empty",
                                PGYER_APP_KEY     : "your_actual_key_or_empty",
                                BUGLY_APPID       : "your_actual_key_or_empty",
                                BUGLY_ENABLE_DEBUG: "false"
        ]
    }

    applicationVariants.all { variant ->
        //修改打包的apk名字
        variant.outputs.all {
            def dateStr = new SimpleDateFormat("MMddHHmm", Locale.US).format(new Date())
            def shortAppId = "${defaultConfig.applicationId}".substring("${defaultConfig.applicationId}".lastIndexOf(".") + 1)
            def versionTag = variant.buildType.name.charAt(0)
            outputFileName = "${shortAppId}-${vname}${versionTag}(b${vcode})-${dateStr}.apk"
        }
    }

    sourceSets {
        main {
            java.srcDirs += 'build/generated/source/greendao'
            assets.srcDirs += "$projectDir/schemas"
            jniLibs.srcDirs = ['libs']
            res.srcDirs = [
                    'src/main/res/'
            ]
        }
    }

    lint {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/rxjava.properties'
        exclude 'META-INF/androidx.exifinterface_exifinterface.version'
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }

    buildTypes {
        //todo 通用的配置
        def appTag = "\"" + "${defaultConfig.applicationId}".substring("${defaultConfig.applicationId}".lastIndexOf(".") + 1) + "\""
        def useExternalDatabase = true
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            shrinkResources true
            signingConfig signingConfigs.config
            buildConfigField "String", "APP_TAG", "${appTag}"
            buildConfigField "boolean", "EXTERNAL_DB", "${useExternalDatabase}"
        }
        debug {
            signingConfig signingConfigs.config
            buildConfigField "String", "APP_TAG", "${appTag}"
            buildConfigField "boolean", "EXTERNAL_DB", "${useExternalDatabase}"
        }
    }

    flavorDimensions = ["default"]

    productFlavors {
        //todo 渠道打包配置配置
        // 发布环境
        production {
            dimension "default"
            resValue "string", "app_name", 'SFW'
            buildConfigField "String", "BUGLY_APPID", '"ccced6668f"'
            buildConfigField "boolean", "LOG_TO_FILE", 'true'
            buildConfigField "boolean", "IS_INTRANET", 'true'
            manifestPlaceholders = [AMAP_API_KEY      : "b46c4981b8e07d4d613867e03c753f4b",
                                    PGYER_API_KEY     : "8c9438bcab1415568aa14299358af9f7",
                                    PGYER_APP_KEY     : "88470f142b1734c12f5bf9f9b3303cea",
                                    BUGLY_APPID       : "ccced6668f",
                                    BUGLY_ENABLE_DEBUG: "true"
            ]
        }
        // 测试环境
        beta {
            dimension "default"
            applicationId "${defaultConfig.applicationId}.beta"
            resValue "string", "app_name", 'SFW-beta'
            buildConfigField "String", "BUGLY_APPID", '"ccced6668f"'
            buildConfigField "boolean", "LOG_TO_FILE", 'true'
            buildConfigField "boolean", "IS_INTRANET", 'false'
            manifestPlaceholders = [AMAP_API_KEY      : "b46c4981b8e07d4d613867e03c753f4b",
                                    PGYER_API_KEY     : "8c9438bcab1415568aa14299358af9f7",
                                    PGYER_APP_KEY     : "88470f142b1734c12f5bf9f9b3303cea",
                                    BUGLY_APPID       : "ccced6668f",
                                    BUGLY_ENABLE_DEBUG: "true"
            ]
        }
        // 开发
        develop {
            dimension "default"
            applicationId "${defaultConfig.applicationId}.dev"
            resValue "string", "app_name", 'SFW-dev'
            buildConfigField "String", "BUGLY_APPID", '"ccced6668f"'
            buildConfigField "boolean", "LOG_TO_FILE", 'false'
            buildConfigField "boolean", "IS_INTRANET", 'false'
            manifestPlaceholders = [AMAP_API_KEY      : "b46c4981b8e07d4d613867e03c753f4b",
                                    PGYER_API_KEY     : "8c9438bcab1415568aa14299358af9f7",
                                    PGYER_APP_KEY     : "88470f142b1734c12f5bf9f9b3303cea",
                                    BUGLY_APPID       : "ccced6668f",
                                    BUGLY_ENABLE_DEBUG: "true"
            ]
        }
    }

}

repositories {
    flatDir {
        dirs 'libs'
    }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}


dependencies {
//       implementation 'com.github.Skeaner:SkeanFrameWork:1.2.4'
    implementation project(path: ':skeanframework')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    kapt 'org.greenrobot:eventbus-annotation-processor:3.1.1'
    kapt "androidx.room:room-compiler:2.5.0"
}
